# Generated by Django 5.1.4 on 2025-01-02 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_subscription_active"),
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Оплата", "verbose_name_plural": "Оплата"},
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_link",
            field=models.URLField(
                blank=True,
                help_text="Введите ссылку на оплату",
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Введите ID сессии",
                max_length=255,
                null=True,
                verbose_name="ID сессии",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Введите курс",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="Введите урок",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.lesson",
                verbose_name="Урок",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("Cash", "Наличные"), ("Transfer", "Перевод на счет")],
                default="Cash",
                help_text="Выберите способ оплаты",
                max_length=15,
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_sum",
            field=models.PositiveIntegerField(
                help_text="Введите сумму платежа", verbose_name="Платеж"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                help_text="Введите пользователя",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
