# Generated by Django 5.1.4 on 2024-12-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="active",
            field=models.BooleanField(default=False, verbose_name="Активность"),
        ),
    ]
